##########################################
# Evaluation Parameters
##########################################
# seed: 42        # Common seed across all source of randomness
batch_size: 
  smallscale: 2048 # Fixed
  largescale: 256 # Fixed
pred_save: 1    # Set as '1' if you want to save the prediction results
oscr_save: 1    # Set as '1' if you want to save the oscr curve data

##########################################
# Data Parameters
##########################################
data:
  smallscale:
    root: /local/scratch/hkim # EMNIST path
    label_filter: [-1]        # [-1] for no filtering. ex. [1,2] only use sample '1' and '2'
  largescale:
    root: /local/scratch/datasets/ImageNet/ILSVRC2012 # ILSVRC2012 path
    protocol: ../../data/LargeScale # ImageNet Protocol root path
    # level: 2 # 1 2 3
  train_neg_size: -1 # -1 for using all. SmallScale : < 42240  LargeScale_1 : LargeScale_2 : LargeScale_3 : 

##########################################
# Architecture Parameters
##########################################
arch:
  model_root: ../../_models
  feat_dim: -1   # -1 for using default value.

osovr_sigma:      # LeNet_plus_plus : 6     LeNet : 8       ResNet_50 : 8
  LeNet_plus_plus: 6
  LeNet: 8
  ResNet_50: 8