##########################################
# Evaluation Parameters
##########################################
seed: 42        # Common seed across all source of randomness
batch_size: 
  smallscale: 2048 
  largescale: 64
pred_save: 1    # Set as '1' if you want to save the prediction results
need_sync: 0    # Set as '1' if the model is trained with the reference code.

##########################################
# Data Parameters
##########################################
data:
  smallscale:
    root: /local/scratch/hkim # EMNIST path
  largescale:
    root: /local/scratch/datasets/ImageNet/ILSVRC2012 # ILSVRC2012 path
    protocol: ../../data/LargeScale # ImageNet Protocol root path
    level: 1 # 1 2 3

##########################################
# Architecture Parameters
##########################################
arch:
  model_root: ../../_models # ../../_models_fc_dim_2
  force_fc_dim: -1 # Set the feature dimensionality on purpose. -1 : feature space dimension == num of classes
