##########################################
# Evaluation Parameters
##########################################
batch_size: 
  smallscale: 2048 # Fixed
  largescale: 256 # Fixed
pred_save: 1    # Set as '1' if you want to save the prediction results
openset_save: 1    # Set as '1' if you want to save the openset performance data

##########################################
# Data Parameters
##########################################
data:
  smallscale:
    root: /local/scratch/hkim # EMNIST path
  largescale:
    root: /local/scratch/datasets/ImageNet/ILSVRC2012 # ILSVRC2012 path
    protocol: ../../data/LargeScale # ImageNet Protocol root path

##########################################
# Architecture Parameters
##########################################
arch:
  model_root: ../../_models
  feat_dim: -1  # -1 for using default value.
